version: '3.7'
services:
  postgres:
    image: postgres:12.0-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=app
  mysql:
    image: mysql:8.0.18
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
  nodejs:
    build: ./gate-simulator
    ports:
      - '9999:9999'